### ISSUE TITLE
Conflict with Extra Utilities 2

### ISSUE THREAD

**Issue by Machine-Maker** [CyclopsMC/StructuredCrafting#13]
Extra Utilities 2 adds mini chests which are crafted by putting one chest into a crafting slot which makes 9 mini-chests. Maybe check to see if the chest is empty before getting rid of the chest and placing the mini-chests. I could not get it to work with a single input recipe and had to use a diffferent type of storage for the input

**Comment by rubensworks** [comment]
That should not happen indeed, thanks for reporting.
