### ISSUE TITLE
Mod not working in 1.12.2?

### ISSUE THREAD

**Issue by rmonk** [CyclopsMC/StructuredCrafting#14]
#### Issue type: :bug:
____
#### Steps to reproduce the problem:

1. Place down a structured crafter, pointed left
2. place 4 planks to the right of it, like in the tutorial images
3. place a switch on the block and flip it

Nothing happens at all.  I tried multiple recipes, even just a log -> planks test.  It's like it's not detecting anything at all.

I'm happy to test anything you'd like to try.
____
#### Versions:

- This mod: 1.12-0.1.10
- CyclopsCore: 1.12.2-0.10.22
- Minecraft: 1.12.2
- Forge: 14.23.0.2531

#### Log file:

There's nothing at all in the logs, no errors, nothing.

**Comment by rmonk** [comment]
After some more testing, it seems it only will work when placed arrow-down?

**Comment by rubensworks** [comment]
Are you sure the crafter is not just placed on the ground, which causes the ground blocks to be included in the crafting recipe?

**Comment by rmonk** [comment]
.. I am a doofus.  That's exactly what it is.  Sorry about that.
