### ISSUE TITLE
Massive Lag when crafting compressed stone

### ISSUE THREAD

**Issue by Machine-Maker** [CyclopsMC/StructuredCrafting#15]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug
- :snail: Performance issue

____
#### Short description:
so making compressed stone lags the server like crazy for me and everyone else online. It went down to 5 TPS out of 20 until I hit the lever to turn off the crafter

EDIT: after the fact I tried it with rock grinders in the same 3x3 pattern for a compressed rock grinder and the same thing happened

#### Expected behaviour:
crafting compressed stone

#### Actual behaviour:
lags like crazy

#### Steps to reproduce the problem:

1. Setup 9 inventories full of stone and an output chest
2. flip lever and boom, lag

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.10
- CyclopsCore: 0.10.22
- Minecraft: 1.12.2
- Forge:

**Comment by rubensworks** [comment]
Can you provide me with an `.nps` file as described [here](https://github.com/CyclopsMC/StructuredCrafting/blob/master-1.12/.github/CONTRIBUTING.md#performance-issues-snail)?

**Comment by Machine-Maker** [comment]
Unfortunately, I do not run the server so I don’t have access to that information. It’s a very small server so I will ask for it.

**Comment by rubensworks** [comment]
Ok, thanks, will put this on hold until then, as it's pretty difficult to debug these kind of things without it.

**Comment by rubensworks** [comment]
@X1machinemaker1X Any news on the nps file?
