### ISSUE TITLE
Deleting inventories and failing to craft

### ISSUE THREAD

**Issue by davqvist** [CyclopsMC/StructuredCrafting#17]
- :bug: Bug

____
#### Short description:
When trying to craft the Stone Rock Grinder from Sky Resources 2, 2 of the inventories get deleted and the recipe fails to craft, same with Iron Rock Grinder.

#### Expected behaviour:
That the recipes craft as expected and mainly the inventories don't get deleted.

#### Actual behaviour:
See above

#### Steps to reproduce the problem:

Modpack Modern Skyblock 2, but also reproducible with my WIP modpack
1. Place Chest (or any other inventory)
2. Place Structured Crafter facing Chest
3. Place 3 Chests in diagonal pattern (or any other inventory)
4. Put Stone (or Iron) in the top 2 chests and sticks in the bottom one
5. Place Lever on Structured Crafter
6. Activate Lever
7. Inventories get deleted and items fall on the ground

Possible cause:
As the structured crafter then crafts with the one remaining cobblestone or Iron Ingot, I assume the 2 inventories get deleted because it found the one cobblestone recipe first. But surely it should check for a "better/full" recipe first and secondly should never delete the inventories.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 0.1.11
- CyclopsCore: 0.10.23
- Minecraft: 1.12.2
- Forge: 2549 (in my WIP pack)

**Comment by rubensworks** [comment]
Can you try reproducing this with just this mod installed for a vanilla recipe?

As I don't know what this Rock Grinder is, or what its recipe is. It may or may not be conflicting with other recipes.

**Comment by davqvist** [comment]
Yeah give me a bit, but you can just install MS2 and follow the steps explained, but I will try to replicate, the problem is though that I need to find a recipe where this happens as well, if my guess that I mentioned is true.

**Comment by davqvist** [comment]
Try a clock or a compass

**Comment by davqvist** [comment]
Yes, tried now in a new instance trying to craft a clock. Deleted every (trapped) chest expect one to craft Gold Nuggets

**Comment by rubensworks** [comment]
Thanks for checking, will look into it.
