### ISSUE TITLE
Non-breaking/placing?

### ISSUE THREAD

**Issue by duckwagon** [CyclopsMC/StructuredCrafting#24]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

My favorite autocrafter for sure. In-world is definitely the way to go, and I like how it integrates into redstone contraptions. I feel like autocrafting is one of those really potentially game-breaking or theme-breaking things. At least for the vanilla+ style play.

The other concern I have (At least in considering coding my own mods, heh) is block placers/breakers. Especially if they don't consider mining levels, or it's instant? If it's at no cost? I dunno, I just feel it's super game-breaking, and I wonder if there's a way to 'balance' that. I dunno if there's a vanilla-style cost you could use, though. 

So I guess my request might be (a) a config to disable actual block placement/breaking, and only read inventories, spit items? Or more ambitious, (b) add in a fuel/cost, break time, and/or harvest level considerations? Maybe for utility, (c) a consistent block breaker and/or placer might be a really nice addition for redstone contraption builds. Maybe the crafter could read off of inventories, or the target of a block breaker, instead of breaking the block itself. Maybe similarly require a block-placer to put it down. Something like that.

Just some thoughts. Options.

**Comment by rubensworks** [comment]
> a config to disable actual block placement/breaking, and only read inventories, spit items?

This sounds like a good idea, I can look into that. The other may be a bit out-of-scope for this mod.
