### ISSUE TITLE
Nbt crafting miss

### ISSUE THREAD

**Issue by sysyss** [CyclopsMC/StructuredCrafting#29]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Crafting nbt Problem?
#### Steps to reproduce the problem:
1. place shulker box.
2. input test item.
3. break shulker box
4. blank output of struct crafter
5. craft dying shulk box recipe(one dye and one shulker box)

#### Expected behaviour:

should shulker box keep do not lost its item

____

#### Versions:

- This mod: 1.18.1-0.22
- Minecraft: 1.18.1
- Forge: 39.0.75

Extra
1. this bug didn't act when output has chest.
2. shulker box has item, then placing shulker box didn't use recipe

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
So the problem is that the contents of the shulker box are lost when using it in a crafting recipe (e.g. to color it)?

**Comment by sysyss** [comment]
yes. if out put is air than place empty shulker box
