### ISSUE TITLE
Dupe: Input items not consumed when recipe output will not fit in output inventory.

### ISSUE THREAD

**Issue by kalutro** [CyclopsMC/StructuredCrafting#31]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Semi-dupe: Structured Crafter consumes no items if the output of the recipe is more than will fit in the inventory. This is done using the Seaopolis 2 modpack.

#### Steps to reproduce the problem:

I used both Minecraft chests and Drawers for testing.

1. Place two inventories for the input items. I used drawers with logs.
2. Place Structured Crafter with lever.
3. Place one inventory for the output items. I used a drawer with downgrade mod so it only fits one stack.
4. Activate the lever and wait for the output inventory to fill.
5. Once full, remove one item from the output inventory.

The issue occurs when the output inventory cannot hold the recipe output. In my example, the recipe produces 16 Stick. If I remove one Stick, another batch will be crafted, but no input items are consumed. If I were to use a pipe to extract 4 Stick per second, I would essentially have infinite Stick, as 4 is less than the recipe output of 16.

#### Expected behaviour:

Input items should be consumed on craft or no crafting should be done if the recipe output will not fit in the output inventory.
____

#### Versions:

- This mod: StructuredCrafting-1.19.2-0.2.4
- Minecraft: 1.19.2
- Forge: 43.2.3

**Comment by rubensworks** [comment]
Thanks for reporting!
