### ISSUE TITLE
[enhancement] ignore empty inventories for crafting

### ISSUE THREAD

**Issue by kreezxil** [CyclopsMC/StructuredCrafting#5]
Realized that when you  use  a bank of chests for crafting, that if for example you have 9 iron chests arranged in a 3x3 grid. And you put iron ingots in 3 of those chests in a bucket pattern, that when you turn on the system nothing happens.

If you remove all the chests that are empty, then the buckets will be crafted.

Add just one function that if an inventory is empty for the purpose of crafting it is treated as an air block.

**Comment by rubensworks** [comment]
This actually sounds like a bug even. Probably introduced in the 1.11 update.
