### ISSUE TITLE
Blocks with inventories can't be used in crafting unless they're inside of other inventories

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/StructuredCrafting#6]
If a block has an inventory, it won't get used in crafting if it's placed directly in the world. Example:
![2017-08-05_21 38 33](https://user-images.githubusercontent.com/16061266/28999868-028af35e-7a27-11e7-938f-5ccd63873e4f.png)
I was trying to craft a trapped chest from a tripwire hook and a regular (empty) chest. Nothing happened when I pressed the button. When I put a chest inside of that chest, then it used the inside chest and crafting worked. The same problem happens if you try to craft a minecart with furnace, but with the furnace in the world instead of in an inventory.

**Comment by rubensworks** [comment]
MC version?

**Comment by josephcsible** [comment]
Minecraft 1.12.1
Forge 14.22.0.2444
Cyclops Core 0.10.12
Structured Crafting 0.1.8
