### ISSUE TITLE
Unexpected behavior when using chest of chests

### ISSUE THREAD

**Issue by josephcsible** [CyclopsMC/StructuredCrafting#8]
When #6 was fixed, blocks in the world were given priority in the two sets of checks, rather than items in inventories, which leads to unexpected and undesired behavior. For example, consider a chest of minecarts and a chest of chests hooked up to a structured crafter, to make "Minecart with Chest"s. The crafter will take the "outside" chest of chests, resulting in all of the "inside" chests dropping as items. It should instead prefer to take an "inside" chest.

**Comment by josephcsible** [comment]
Actually, I wonder if it would make more sense to split the structured crafter into a structured item crafter and a structured world crafter. I imagine that there will always be ambiguous situations like this one.

**Comment by rubensworks** [comment]
Inventories should be given a preference, so that sounds like a bug.

**Comment by rubensworks** [comment]
Have you tested this behaviour? Because I can't seem to reproduce it here. It works as intended for me: inventories are given preference over blocks.

**Comment by josephcsible** [comment]
Weird, I did test this earlier, but I just tried again and can't reproduce it. I'll play with it a little more to see if I can figure out what else I did, and I guess I'll just close it if I can't figure it out.

**Comment by josephcsible** [comment]
And I've got nothing. If it ever happens again, this can always be reopened.
